### PR TITLE
Update README.md topic link

### PR DESCRIPTION
**Pull request by nkujomiru**

### CODE REVIEW

**Comment by nkujomiru** [comment]
"git-topic/ " link goes to Not Found page.
Fixed to "doc/git-topic"

**Comment by phdru** [comment]
> "git-topic/ " link goes to Not Found page. Fixed to "doc/git-topic"

I do not understand the problem. It's just a directory, there shouldn't be any problems with or without the trailing slash. Both URLs https://github.com/GitAlias/gitalias/tree/main/doc/git-topic/ and https://github.com/GitAlias/gitalias/tree/main/doc/git-topic show me the same directory.

**Comment by nkujomiru** [comment]
You're right, I made some unnecessary changes, sorry.
It's this link that doesn't work for me:
`[git topic-*](git-topic/)`
I changed it to 
`[git topic-*](doc/git-topic/)`

**Review by phdru — APPROVED** [review]

**Comment by joelparkerhenderson** [comment]
Good thank you!

**Pull request merged**
