### PR TITLE
Add discard and discard-all aliases

### PR DESCRIPTION
**Pull request by pachoyan**
Add `discard` and `discard-all` aliases:

 Usages:
   
#### Discards files

     git discard file-name

- Parameter would be the file name or pattern to discard

#### Discards working directory

      git discard-all

- Discards all the working directory.

--- 
Why discard? 

It is an action which is used in several git GUIs, for example Source Tree.

### CODE REVIEW

**Comment by phdru** [comment]
`discard-all` seems to be equivalent to `reset --hard HEAD`, right?

May I ask you to describe it a bit better? Something like
    # Discard uncommitted changes in a (list of) file(s)

**Comment by pachoyan** [comment]
Of course!, I'll change the description to `# Discard uncommitted changes in a (list of) file(s)` . 

--- 

On the other hand, discard-all is not equivalent to `reset --hard HEAD`, not at all. `discard-all` discards updates and untracked files from working tree, otherwise `reset --hard HEAD`  discards changes from both: stage area (index) and working tree.

Let me explain it:
Sometimes, IMO is useful is to add some file(s) to your stage area (index) and discard the others.
For example, if you are working in something and it is finished (prepared to commit), then you have an idea but you are not sure if it is good or not, so you can add your changes to the stage area, prove your idea and if it is not a good just discard working tree changes, and commit the prepared (changes in stage area).

**Comment by phdru** [comment]
Ok, go on. I recommend to amend your commit and force-push it to avoid cluttering git logs.

**Comment by joelparkerhenderson** [comment]
Good idea, thanks!

What's your opinion of the concept of discard? Should it do a clean or not?

I would expect something like this:

    discard = checkout --
    discard-all = checkout -- . 

Or something like this:

    discard = !git clean -df && git checkout --
    discard-all = !git clean -dffx && git checkout -- :/  (Wh

I would not expect one alias to do `clean`, and the other to not do `clean`. 

Maybe there's a word that's more semantic than "all" to mean your intent of "plus do a clean before"?

**Comment by pachoyan** [comment]
@joelparkerhenderson you made me think about that, and you're right, it should be two different concepts. Until now, my concept of discard-all was clean the working tree, but actually, it should be clean.

On the one hand, we could have two aliases to discard the changes of tracked files in the working tree (one for specific files, and other for all files) (index or stage area is not discarded). They would the `discard aliases`:

    discard = checkout --
    discard-all = checkout -- .

On the other hand, we could have the clean aliases, which cleans the working tree (index or stage area is not cleaned).

I propose these:

     clean-working-file <file name>
     clean-all-working

Or these:

    clean-file <file name>
    clean-all

What do you think? Which names do you propose?

**Comment by joelparkerhenderson** [comment]
I like this one:

    discard = checkout --

I like it because it's semantic, and user friendly, and easy to use with a variety of paths such as:

    discard example.txt
    discard .
    discard :/ 

For the clean concept, how about the word "cleanout"? Because it's a hybrid of "clean" and "checkout". 

    cleanout = !git clean -df . && git checkout -- .

Could it help to have paths? For example something like this:

    cleanout = !"f() { paths=${@:-.}; git clean -df \"$paths\"; git checkout -- \"$paths\"}; f"

**Comment by pachoyan** [comment]
I've added the discard alias:

    discard = checkout --

Also the cleanout (I like this name) but I decided to not have paths. Just apply the `clean-out` in the working tree.
So, the alias is like next:

    cleanout = !git clean -df && git checkout -- .

It cleans the working tree and also discards the changes.

**Comment by joelparkerhenderson** [comment]
Excellent. Thank you so much for your work and your discussion!

**Pull request merged**
