### PR TITLE
chore: rename markdown doc for convenient browsing

### PR DESCRIPTION
**Pull request by benelan**
Renamed all of the markdown files in `/doc` from `index.md` to `readme.md` so that they are easily browsable on GitHub.

```sh
find . -name 'index.md' -type f -exec sh -c '
for f; do
    mv "$f" "${f%/*}/readme.md"
done' sh {} +
```

### CODE REVIEW

**Comment by joelparkerhenderson** [comment]
Thanks for the PR. Is it the case that you would broadly want this kind of effect (i.e. GitHub rendering) for all files named `index.md` in all repos for all users? 

If so, I'd like to ask GitHub to add the feature for everyone. This is because there are a bunch of files like this, such as thousands of blogs, that all use *.md files, that could benefit from automatic rendering.

**Comment by benelan** [comment]
I don't think there needs to be any changes on GitHub's end. For consistency, the convention is that only `readme.md` renders. What if there is a directory with both `index.md` and `readme.md` files, which would render?

**Comment by joelparkerhenderson** [comment]
> For consistency, the convention is that only readme.md renders.

It's a bit trickier than that. GitHub has a very long convention of breaking things, including common markdown, and rendering things in unconventional ways. 

For example, see GitHub flavored markdown and the various special GitHub files which change much more often than the longtime web convention of having a directory with 'index.*' being a default to render to the user. Same thing with front matter, such as using HTML comments, YAML structure, JSON data, or GitHub's TOML.

> What if there is a directory with both index.md and readme.md files, which would render?

The index.* is the longtime web convention.

**Comment by benelan** [comment]
Yeah, I guess I should have specified that `readme.md` is the __GitHub convention__; I'm aware of the ubiquitous use of `index`. I never ran into any issues due to GitHub's convention, but I can definitely see the use case for allowing people to specify what gets rendered. 

It could be even be specified in a config file, e.g. `/.github/rendering.yml`. In my opinion, we would want to keep the default as `readme.md`, at least until the messaging gets across.

That being said, since this repo is on GitHub, I still think it's worth following their convention for now. If/when they install the enhancement, it is really easy to change back using the script I included above.

**Comment by joelparkerhenderson** [comment]
Your way is better with `rendering.yml`. Want to ask the GitHub folks? Generally they are very good about considering ideas like these, especially because your point helps reduce bias of cross-cultural communication, and also improves capabilities for lots of developers. I see your idea as win-win-win. 

> That being said, since this repo is on GitHub, I still think it's worth following their convention for now.

Well, the repo is involved in a lot of places, including webservers, bookmarks, and blog pipelines that use `index.md` as a specialized file-- so it's kind of a choice between the repo working with every open source developer and open source tool and open source convention, or forcing the repo to break because of Microsoft's hardcoded bias.

The previous two times I've seen this happen, MIcrosoft did the right thing, and fixed the naming areas. So I'm hopeful Microsoft will listen to your idea and take it seriously.

In the meantime, to get you want you want ASAP, could it work OK for you if your script copies index.md to readme.md? This means two files, which isn't totally ideal, yet does get you a pragmatic solution for now. What do you think?

**Comment by benelan** [comment]
Ah, I didn't realize the repo is used in other applications that require the filename to be `index.md`. After taking another look, there are [links to `index.md`](https://github.com/GitAlias/gitalias/blame/main/doc/index.md#L55) in the repo itself as well, which would need to change. 

I think that's another good use case for allowing the user to choose their rendering preference. In my opinion, having duplicate files is a bit overkill, so I can close this PR. I have my fork that I can use in the meantime.

**Comment by joelparkerhenderson** [comment]
OK good. If you've heard of "Chesterton's Fence", that's the kind of idea of the repo links that you correctly mention. (Or if you're new to the fence, it's a nifty shorthand)

**Pull request closed without merging**
