### PR TITLE
Add git config command to include gitalias file

### PR DESCRIPTION
**Pull request by yantaozhao**
1. Add a handy way that using `git config` command to include this file into config file.

### CODE REVIEW

**Comment by yantaozhao** [comment]
you mean the 2nd commit?
I think it's a good addition as described above. so append to the PR too.

**Comment by joelparkerhenderson** [comment]
Thank you! Yes the git config instruction is good addition

Can you help me understand your purpose for the second commit, for the `--decorate` setting? 

My general understanding is that `--decorate` is the default, and has been for a few years now. 

My general understanding is that the `--decorate` option has a way to set it in the config file by running `git config --global log.decorate auto`. 

I would like to do your idea of the git config instruction. Would you prefer to adjust this PR to have just that commit, or prefer to send a new PR with just that commit, or prefer to skip the PR and have me to edit the file on my side?

Thank you too @phdru for the review, as always much appreciated

**Comment by yantaozhao** [comment]
> Thank you! Yes the git config instruction is good addition
> 
> Can you help me understand your purpose for the second commit, for the `--decorate` setting?
> 
> My general understanding is that `--decorate` is the default, and has been for a few years now.
> 
> My general understanding is that the `--decorate` option has a way to set it in the config file by running `git config --global log.decorate auto`.
> 
> I would like to do your idea of the git config instruction. Would you prefer to adjust this PR to have just that commit, or prefer to send a new PR with just that commit, or prefer to skip the PR and have me to edit the file on my side?
> 
> Thank you too @phdru for the review, as always much appreciated

All right, I'v deleted the commit with `--decorate`.

**Comment by yantaozhao** [comment]
After looking up the `git` release notes, found that the `--decorate` option in `git log` was enabled default since [git v2.13](https://github.com/git/git/blob/master/Documentation/RelNotes/2.13.0.txt#L176).  :sun_with_face:

**Comment by joelparkerhenderson** [comment]
Excellent, thank you!

**Pull request merged**
