### PR TITLE
Add 'incoming' and 'outgoing' aliases

### PR DESCRIPTION
**Pull request by phdru**

### CODE REVIEW

**Comment by kissgyorgy** [comment]
Hi @phdru, could you tell a legit use case for `push2all`?

**Comment by phdru** [comment]
@kissgyorgy: push branch(es) to all configured remotes:

```sh
git remote add origin git@github.com:GitAlias/gitalias.git
git remote add gh git@github.com:phdru/gitalias.git
git push2all
git push2all master
```
push configured branches or just master to `origin` and `gh`.

**Comment by phdru** [comment]
@kissgyorgy even better example: I regularly push SQLObject to [Github](https://github.com/sqlobject),  [Gitlab](https://gitlab.com/sqlobject) and  [SourceForge](https://sourceforge.net/p/sqlobject/_list/git).

**Comment by joelparkerhenderson** [comment]
I have this use case in practice too; my current work project pushes to multiple remotes.

What do you all think of calling this "push-remotes"? (I'm aiming to not use "2" to mean "to" because teams has many non-native-English speakers)

**Comment by phdru** [comment]
@joelparkerhenderson `push-remotes` sounds strange for me: push remotes to where? May be name it `push-to-remotes`? `push-all-remotes`? `push-to-all`? All of them are too long and far from perfect, so decide yourself.

**Comment by joelparkerhenderson** [comment]
I'm doing push-to-all-remotes because it's the most explanatory; personally I'm going to alias this to "pushes" because it's really handy for my current project.  Thanks for your ideas!

**Comment by phdru** [comment]
Not all of them are mine — I've collected some from public dotfiles repositories, mostly at Github. :smile: But I'm glad there's a place to collect them and use as a point of reference.

**Pull request merged**
