### PR TITLE
Add rename-alias alias at alias management

### PR DESCRIPTION
**Pull request by pachoyan**
Add rename alias:

Usage:
     
    git rename-(local|global)-alias <alias existing name> <new alias name>
<s>git rename-alias <alias existing name> <new alias name></s>

- Choose Local or global to use `--global` or `--local` options
- First parameter `<alias existing name>` must be an existing alias.
- Second parameter `<new alias name>`  must be an alias that does not exist.
- First parameter and second parameter must be different.
- There must be two parameters

Examples:

Success:

    git rename-local-alias ci comm
    git rename-global-alias ci comm
 <s>git rename-alias ci comm</s>
 <s>Alias comm renamed to ci</s>

Error:

    git rename-local-alias any ci
    Usage: git rename-alias <alias existing name> <new alias name>
    The alias you are going to rename must exist and new name must not exist.

    git rename-global-alias any ci
    Usage: git rename-alias <alias existing name> <new alias name>
    The alias you are going to rename must exist and new name must not exist.

 <s>git rename-alias any ci</s>

### CODE REVIEW

**Comment by phdru** [comment]
I don't like that 'Alias … renamed'. Unix command-line commands are usually silent in case of success; you can add option `-v` to allow verbosity.

Other than that — interesting idea and good implementation!

**Comment by pachoyan** [comment]
I agree. I'm going to remove the success message.
Regard the verbosity option IMO is not need. What do you think?

**Comment by phdru** [comment]
Not needed IMO. Go on!

**Comment by pachoyan** [comment]
Success message removed.

**Comment by joelparkerhenderson** [comment]
Good work, thank you! Good code, good commit message, and good discussion.

@pachoyan How does the code distinguish a local alias and a global alias? (The git default is for the "alias" command to work on a local alias, not global. See the --local option and --global option.)

**Comment by pachoyan** [comment]
@joelparkerhenderson Actually it doesn't distinguish a local alias and a global, it is using always the `--global` option. In my next commit, I'm going to update that using the same as is doing in `add-(local-global)-alias`  aliases.

So, in the next commit the usage would be:
- Local 

      git rename-local-alias ci comm

- Global 

      git rename-global-alias ci comm

**Pull request merged**
