### PR TITLE
Add 'calm' short for commit all with a message

### PR DESCRIPTION
**Pull request by akalcik**

### CODE REVIEW

**Comment by joelparkerhenderson** [comment]
Thanks! How often do you personally use this command, without any push?

Do you know about these two?

  * git c -am (this is "c" for commit, then the typical built in -am for --all --message)
  * git put (this is a git alias that does commit --all --message and also does the push)

I'm aiming to make "ca" always "commit --amend" because the "--amend" arg has no short form.

**Comment by akalcik** [comment]
Well I wasn't sure about the abbreviation. I thought  ```cma``` as git --message --all but it wouldn't respect the order. I was aware of ```git put``` as I also had short code for this on my mind but skipped it in this pull request because of this. I know ```git c -am``` but thought shortcut would be better. I'm using it often as I commit only small changes and than push it when everything out when it make sense. I'm open to change the name.

**Comment by felipecrs** [comment]
I have the following:

```
caa = commit --amend --all
caane = commit --amend --all --no-edit
```

And I use `git caane` a lot.

**Comment by joelparkerhenderson** [comment]
@felipecrs Seems reasonable to me... would you like to do a merge request aka PR, or would you prefer I add your two at the next update?

**Comment by joelparkerhenderson** [comment]
Merged in #100.

**Pull request closed without merging**
